---
title: "Visualización de pronósticos"
subtitle: 'Estancia de vinculación '
author: J. Antonio García Ramírez
date: 12 de marzo, 2019
output:
  beamer_presentation:
    theme: "Madrid"
    fonttheme: "structurebold"
header-includes:
   - \usepackage[utf8]{inputenc}
   - \usepackage[spanish]{babel} 
---
---

# Esquema

 * Antecedentes

 * Objetivo
 
 * Motivación

 * Comunicación

 * Delimitación

 * Enfoque(s)

 * Avances (Situación actual)

 * Trabajo (no tan) futuro 
 
 * Comentarios y sugerencias 
 
 * Bibliografía y referencias


# Antecedentes

Observatorio Econométrico: Iniciativa de la unidad Monterrey 

[Boletín del 2012](https://drive.google.com/file/d/1q_G4laOQV3H3UNF2gXZxhEZdacG3rq_R/view?usp=sharing)


[Carlos III](https://e-archivo.uc3m.es/handle/10016/20747#preview)



# Objetivo


**Visualizar los pronosticos** \footnote{Pronósticos precisos y confiables, para la toma de decisiones} **de la [metodología](https://drive.google.com/file/d/1OEoKR1Bz2QQ7Jpp2sx-mvGJm8Xr2bYPD/view?usp=sharing) que se tiene  ¿para qué?**

Automatizar el proceso, en medida de lo posible







# Motivación

\begin{itemize}
\item CIMAT
\item Profesionales
\end{itemize}
    
# Comunicación


\begin{itemize}
\item Mtro. Héctor
\item Dr. Andres  
\item Dr. Francisco C. 



\end{itemize}
    

# Delimitación
    
    Issue(S) : Código, tiempos de ejecución y documentación.
    
# Enfoque(s)

Cascada (abandoned)

Ágil
    
# Avances (Situación actual)
 
 __Primer entregable__


# Trabajo (no tan) futuro 



\begin{itemize}
\item Áreas de oportunidad 
    
\item Criptomonedas



\end{itemize}


# Comentarios y sugerencias
 
    
# Bibliografía y referencias






\begin{thebibliography}{1}

\bibitem{pls}
Bjorn-Helge Mevik and Ron Wehrens;\textit{ The pls Package: Principal Component and Partial Least Squares Regression in R}, Journal of Statistical Software January 2007, Volume 18, Issue 2.




\bibitem{PLSmaths}
Hoskuldsson (1988); \textit{ PLS Regression Methods}, Journal of Chemometrics, Vol 2, pp 221-228



\bibitem{frances}
Philip Hans Franses (2006); \textit{Forecasting 1 to h steps ahead using partial least squares}, Econometric Institute, Erasmus University Rotterdam, Econometric Institute Report
2006-47


\bibitem{interpretation}
P.H. Garthwaite (1994); \textit{An Interpretation of Partial Least Squares},  JASA Vol 89, No 425, pp122-127

\end{thebibliography}

