setwd("~/Documents/GitHub/MCE2/4/Consultoria/Cervezas")
library(lubridate)
dir()
cervezas <- read.csv('Datos_Cerveza_UnaPlaza.txt', sep='|', stringsAsFactors = FALSE)
cervezas$loc <- as.character(cervezas$loc)
cervezas$id_fecha <- ymd(cervezas$id_fecha)
cervezas$id_producto <- as.character(cervezas$id_producto)
sapply(cervezas, class)
catalogo <- read.csv('CATSKU_BI.txt', sep='|', stringsAsFactors = FALSE)
catalogo$PRODUCTO_KEY <- as.character(catalogo$PRODUCTO_KEY)
catalogo$UPC_CVE <- as.character(catalogo$UPC_CVE)
sapply(catalogo, class)
sku.cervezas <- unique(cervezas$id_producto)
library(dplyr)
catalogo %>% filter(PRODUCTO_KEY %in% sku.cervezas) -> catalogo.cervezas
#save(catalogo.cervezas, file = 'catalogoCervezas.rdata')
#save(cervezas, file = 'cervezas.rdata')
load( file = 'catalogoCervezas.rdata')
load( file = 'cervezas.rdata')
library(ggplot2)
names(cervezas)
sapply(cervezas, class)
remove(catalogo)
gc()
Sys.sleep(10)
p1 <- ggplot(cervezas, aes(x=id_fecha, y=cantidad, color=factor(id_producto)))+
    geom_line()+theme_minimal()
p1
